name: CI/CD DevSecOps para FastAPI con CQRS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configurar variables de docker
        id: docker_vars
        run: |
           echo "IMAGE_NAME=invalidtruck/cqrs_fastapi" >> $GITHUB_OUTPUT
           echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT
      
      - name: Iniciar sesion docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name : Build Docker image
        run: |
          uses: docker/build-push-action@v5
          push: false
          tags: ${{ steps.docker_vars.outputs.IMAGE_NAME }}:${{ steps.docker_vars.outputs.IMAGE_TAG }}
          load: true

      - name: Escaneare la imagen docker con trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.docker_vars.outputs.IMAGE_NAME }}:${{ steps.docker_vars.outputs.IMAGE_TAG }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Subir la imagen docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.docker_vars.outputs.IMAGE_NAME }}:${{ steps.docker_vars.outputs.IMAGE_TAG }}

      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: instalar bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit



      - name: Install fastapi
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pydantic pytest

      - name: ejecutar escaneo SAST con bandit
        run: |
          bandit -r app/ -ll -f custom_json -o bandit-report.json || true

      - name: Subir repote de bandit (artifact) 
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.json
          retention-days: 5